### PR TITLE
Check api token

### PR DESCRIPTION
**Pull request by moutyque**
I want to make the API token not mandatory for private isntance of HuggingFace.
Also move the check when the project is loaded and when we change the token.

### CODE REVIEW

**Comment by videogameaholic** [comment]
Honestly, if the goal is for the token to be optional then we might just drop all of the "token is required" notifications entirely.
Leave the bearerToken.isBlank check in StarCoderService and then don't bother checking anywhere else.
There is a TODO in StarCoderService for a notification banner because I thought about a banner on the first time startup with a link to the settings.  That banner could say the token is "recommended" if we don't want it to be required.  The idea for the banner would be that it goes away once it's acknowledged.

**Comment by moutyque** [comment]
Hello,

If the check stay in StarCoderService a message will pop each time the code completion is called which seems to be quiet bothering.
My suggestion will be to make it optional, so change the message from "StarCoder API token is required." to "StarCoder API token is empty."
Keep the check on the settings side to avoid message flooding.

What do you think about it ?

**Comment by videogameaholic** [comment]
Right, let me clarify.  Keep your changes in StarCoderService so that we skip adding the token if it's blank and we don't notify there.  Revert your changes in StarCoderSettings so that we don't notify there.  I was thinking revert your changes in StarCoderSettingsProvider so that we don't notify there either.  However I'm fine with leaving it in StarCoderSettingsProvider if we change it to "StarCoder API token is recommended" or "StarCoder API token is suggested."  Notifying when saving is probably sufficient.  If they've specifically decided not to set a token then we don't necessarily need to notify every time we start up.

**Comment by moutyque** [comment]
Did not get the time earlier to make the modification. I did it now.

**Pull request merged**
